name: PHPStan

on:
  workflow_call:
    inputs:
      php-version:
        description: 'PHP version to use'
        required: false
        type: string
        default: '8.4'
      timeout-minutes:
        description: 'Timeout for PHPStan in minutes'
        required: false
        type: number
        default: 5

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout-minutes }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3

      - name: Run PHPStan
        run: ./vendor/bin/phpstan --error-format=github